Day-58-Job Portal Project Apply Job (05-06-2024)/jobProject/jobProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from jobProject.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',signup,name='signup'),
    path('',signin,name='signin'),
    path('dashboard/',dashboard,name='dashboard'),
    path('logoutpage/',logoutpage,name='logoutpage'),
    
    # job 
    path('addjob/',addjob,name='addjob'),
    path('viewjob/',viewjob,name='viewjob'),
    path('editjob/<str:jobid>',editjob,name='editjob'),
    path('deletejob/<str:jobid>',deletejob,name='deletejob'),
    path('applyjob/<str:jobid>',applyjob,name='applyjob'),
    
    
    # profile 
    path('baseprofile/',baseprofile,name='baseprofile'),
    path('profileinfo/',profileinfo,name='profileinfo'),
    path('basicprofile/',basicprofile,name='basicprofile'),
    path('recruitercontact/',recruitercontact,name='recruitercontact'),
    path('seekereducation/',seekereducation,name='seekereducation'),
    path('seekerwork/',seekerwork,name='seekerwork'),
    path('changepassword/',changepassword,name='changepassword'),
    path('specificjobpost/',specificjobpost,name='specificjobpost'),
    path('editprofile/',editprofile,name='editprofile'),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Day-58-Job Portal Project Apply Job (05-06-2024)/jobProject/jobApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUserModel(AbstractUser):
    USER_TYPE={
        ('seeker','Job Seeker'),
        ('recruiter','Job Recruiter'),
    }
    user_type=models.CharField(choices=USER_TYPE,max_length=100)
    city=models.CharField(max_length=100)
    GENDER={
        ('male','Male'),
        ('female','Female'),
        ('others','Others'),
    }    
    gender=models.CharField(choices=GENDER,max_length=100)
    profile_picture=models.ImageField(upload_to='media/profile_picture')
    
    # basic info 
    father_name=models.CharField(max_length=100)
    mother_name=models.CharField(max_length=100)
    hobby=models.CharField(max_length=100)

    def __str__(self):
        return self.username

class RecruiterModel(models.Model):
    # contact
    mobile_number=models.CharField(max_length=100)
    company_address=models.CharField(max_length=100)
    
    recruiter_user=models.OneToOneField(CustomUserModel,on_delete=models.CASCADE,related_name='recruitermodel')
    
    def __str__(self):
        return self.recruiter_user.username
    
class SeekerModel(models.Model):
    # education
    edu_name=models.CharField(max_length=100)
    edu_institute=models.CharField(max_length=100)
    edu_location=models.CharField(max_length=100)

    # work exprerience
    work_name=models.CharField(max_length=100)
    work_location=models.CharField(max_length=100)
    work_time=models.CharField(max_length=100)
    
    seeker_user=models.OneToOneField(CustomUserModel,on_delete=models.CASCADE,related_name='seekermodel')
    def __str__(self):
        return self.seeker_user.username
    
class JobModel(models.Model):
    job_title=models.CharField(max_length=100)
    company_description=models.TextField()
    company_logo=models.ImageField(upload_to='media/company_logo')
    company_name=models.CharField(max_length=100)
    company_location=models.TextField()
    qualifications=models.CharField(max_length=100)
    deadline=models.DateField()
    salary=models.CharField(max_length=100)
    created_by=models.ForeignKey(CustomUserModel,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.created_by.username

class ApplyJobModel(models.Model):
    applicant=models.ForeignKey(CustomUserModel,on_delete=models.CASCADE,related_name='applicantinfo')
    applied_job=models.ForeignKey(JobModel,on_delete=models.CASCADE)
    skills=models.CharField(max_length=100)
    resume = models.FileField(upload_to='media/seeker_resume')
    seeker_profile_pic = models.ImageField(upload_to='media/seeker_profile_pic')
    qualifications = models.TextField()
    def __str__(self):
        return self.applicant.username
    

Day-58-Job Portal Project Apply Job (05-06-2024)/jobProject/templates/common/base.html
<!DOCTYPE html>
<html>
<head>
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover:not(.active) {
  background-color: #111;
}

.active {
  background-color: #04AA6D;
}
</style>
</head>
<body>

{% include 'common/navbar.html' %}


{% block content %}
    
{% endblock content %}


</body>
</html>



Day-58-Job Portal Project Apply Job (05-06-2024)/jobProject/templates/common/dashboard.html
{% extends 'common/base.html' %}


{% block content %}
<h1>This is dashboard</h1>
<p>Welcome {{user.username}}</p>
<p>User type: {{user.get_user_type_display}}</p>

{% endblock content %}
    

Day-58-Job Portal Project Apply Job (05-06-2024)/jobProject/templates/common/messages.html

{% if messages %}
    
    {% for message in messages %}
        
        {% if message.tags == 'warning' %}
            <p>{{message}}</p>
        {% endif %}
            
    {% endfor %}
        
{% endif %}
    

Day-58-Job Portal Project Apply Job (05-06-2024)/jobProject/templates/common/navbar.html
<ul>
  
  
  
  
  <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
  
  {% if user.user_type == 'recruiter' %}
  
  <li><a href="{% url 'addjob' %}">Add Job</a></li>
  {% endif %}
  
  <li><a href="{% url 'viewjob' %}">View Job</a></li>

    <li style="float:right"><a href="{% url 'logoutpage' %}">Logout</a></li>
    <li style="float:right"><a class="active" href="{% url 'baseprofile' %}">Profile</a></li>
  

  </ul>

Day-58-Job Portal Project Apply Job (05-06-2024)/jobProject/templates/common/signin.html
<!DOCTYPE html>
<html>
<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
<body>

<h3>Sigin page</h3>

<div>
  <form action="{% url 'signin' %}" method="POST">
    {% csrf_token %}
    <label for="fname">Username</label>
    <input type="text" id="fname" name="username">
    <label for="fname">Password</label>
    <input type="password" id="fname" name="password">
    <input type="submit" value="Submit">
</form>
<a href="{% url 'signup' %}">Don't have an account?</a>
</div>

</body>
</html>



Day-58-Job Portal Project Apply Job (05-06-2024)/jobProject/templates/common/signup.html
<!DOCTYPE html>
<html>
<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
<body>

<h3>Signup page</h3>

<div>
  <form action="{% url 'signup' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="fname">Username</label>
    <input type="text" id="fname" name="username">
    <label for="fname">Password</label>
    <input type="password" id="fname" name="password">
    <br><br>
    <label for="fname">Confirm Password</label>
    <input type="password" id="fname" name="confirm_password">
    <br><br>
    <label for="country">Select role</label>
    <select id="user_type" name="user_type">
        <option value="seeker">Job Seeker</option>
        <option value="recruiter">Job Recruiter</option>
    </select>
    <label for="fname">City</label>
    <input type="text" id="fname" name="city">
    <label for="country">Select Gender</label>
    <select id="user_type" name="gender">
        <option value="male">Male</option>
        <option value="female">Female</option>
        <option value="others">Others</option>
    </select>
    <label for="fname">Profile Picture</label>
    <input type="file" id="fname" name="profile_picture">
    <br><br>
    <label for="fname">Email</label>
    <input type="email" id="fname" name="email">
    
   <input type="submit" value="Submit">
  </form>
  <a href="{% url 'signin' %}">Already have an account?</a>
</div>

</body>
</html>



Day-58-Job Portal Project Apply Job (05-06-2024)/jobProject/templates/common/viewjob.html
{% extends 'common/base.html' %}

{% block content %}
<style>
    .job-cards {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
    }
    
    .job-card {
      width: calc(33.33% - 20px); /* Adjust width based on your design */
      background-color: #f5f5f5;
      border-radius: 10px;
      padding: 20px;
      margin-bottom: 20px;
      box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
    }
    
    .job-card h3 {
      margin-top: 0;
      color: #333;
    }
    
    .job-card p {
      color: #666;
    }
    
    .job-card img {
      display: block;
      margin: 10px auto;
    }
    
    .buttons {
      margin-top: 15px;
    }
    
    .buttons button {
      margin-right: 10px;
      padding: 8px 15px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }
    
    .edit-btn {
      background-color: #4CAF50;
      color: white;
    }
    
    .delete-btn {
      background-color: #f44336;
      color: white;
    }
    
    .view-btn {
      background-color: #008CBA;
      color: white;
    }
    
    </style>
<div class="job-cards">
  {% for i in jobs %}
  <div class="job-card">
    {% include 'common/messages.html' %}
    <h3>Job Title</h3>
    <p>{{i.job_title}}</p>
    <h3>Job Description</h3>
    <p>{{i.company_description}}</p>
    <h3>Company Logo</h3>
    <img src="/{{i.company_logo}}" width="100px" alt="">
    <h3>Company Name</h3>
    <p>{{i.company_name}}</p>
    <h3>Company Location</h3>
    <p>{{i.company_location}}</p>
    <h3>Qualifications</h3>
    <p>{{i.qualifications}}</p>
    <h3>Deadline</h3>
    <p>{{i.deadline}}</p>
    <h3>Salary</h3>
    <p>{{i.salary}}</p>
    <h3>Created By</h3>
    <p>{{i.created_by}}</p>
    <div class="buttons">
      
        {% if user.user_type == 'recruiter' and user == i.created_by %}
      
        <button class="edit-btn"><a href="{% url 'editjob' i.id %}">Edit</a></button>
        <button class="delete-btn"><a href="{% url 'deletejob' i.id %}">Delete</a></button>
        
        {% elif user.user_type == 'seeker' %}
        
        <button class="edit-btn"><a href="{% url 'applyjob' i.id %}">Apply job</a></button>
        
        {% if already_applied %}
            <p>Already applied</p>
        {% endif %}
        
        {% else %}
        
        <button class="edit-btn"><a href="{% url 'signup' %}">Please signup to apply</a></button>
        
        {% endif %}
        
    </div>
  </div>
  {% endfor %}
</div>


{% endblock content %}